import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import devicon from "../../public/devpic2.png";
import Skills from '@/components/Skills'
import Experience from '@/components/Experience'
import Education from '@/components/Education'
import TransitionEffect from '@/components/TransitionEffect'

const about = () => {
  return (
    <>
        <Head>
            <title>Yeoh Han Yi</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="../../public/favicon.ico" />
        </Head>
        <TransitionEffect />
        <main className="flex w-full flex-col items-center justify-center text-dark dark:text-light">
            <Layout className="pt-16">
                <AnimatedText text="About Me" className="mb-16 sm:mb-8" />
                <div className="flex items-center justify-between w-full lg:flex-col gap-10">
                    <div className="w-1/3 md:w-full rounded-2xl border-2 border-solid border-dark bg-light dark:bg-dark dark:border-light p-4">
                        <Image src={devicon} alt="" className="w-full h-auto rounded-2xl" />
                    </div>
                    <div className="w-2/3 flex flex-col item-center self-center lg:w-full lg:text-center">
                        <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                            👋 Hi, I&apos;m Yeoh Han Yi, a Computer Science major with a second major in Statistics at the National University of Singapore, currently navigating the second semester of my freshman year. 
                        </p>
                        <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                            💡 Undecided on a specialization as of now, I&apos;m currently exploring various fields, especially machine learning, full-stack development and software engineering.
                            This eclectic approach allows me to discover where my interests and strengths lie.
                        </p>
                        <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                            🚀 Fueled by a fascination with bleeding-edge technology since young, I see my studies in computer science as a front-row seat to witness the next wave of innovations that will change our lives.
                        </p>
                        <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                            👨‍💻 Although I started my coding journey later than many of my peers, my strong willingness to learn and improve my skills allows me to remain competitive.
                        </p>
                    </div>
                </div>

                <Skills />
                <Experience />
                <Education />
            </Layout>
        </main>
    </>
  )
}

export default about