import Layout from "@/components/Layout";
import TransitionEffect from "@/components/TransitionEffect";
import Head from "next/head";
import Image from "next/image";
import devicon from "../../public/devpic1.png";
import Link from "next/link";
import { BsBoxArrowInRight } from "react-icons/bs";
import ScrambledText from "@/components/ScrambledText";

export default function Home() {
  return (
    <>
        <Head>
            <title>Yeoh Han Yi</title>
            <meta name="description" content="Generated by Create Next App" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="shortcut icon" type="image/x-icon" href="../../public/favicon.ico?" />
        </Head>

        <TransitionEffect />

        <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
            <Layout className="pt-0 md:pt-16 sm:pt-8">
                <div className="flex items-center justify-between w-full lg:flex-col">
                    <div className="w-1/2 md:w-full">
                        <Image src={devicon} alt="Han Yi" className="w-full h-auto md:inline-block md:w-full" 
                        priority
                        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                        />
                    </div>
                    <div className="w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center">
                        <ScrambledText className="!text-5xl !text-left xl:!text-4xl lg:!text-center sm:!text-2xl" />
                        <p className="my-4 text-base font-medium md:text-sm sm:text-xs">I am a freshman studying Computer Science with a second major in Statistics at the National University of Singapore.</p>
                        <p className="my-4 text-base font-medium md:text-sm sm:text-xs">My current interests lie in full-stack development, machine learning and software engineering.</p>
                        <div className="flex items-center self-start mt-2 lg:self-center">
                            <Link href="/resume.pdf" target={"_blank"}
                            className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-gradient-to-r from-blue-500 to-cyan-400 border-2 border-solid border-transparent hover:border-dark duration-300
                            dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                            download={true}>
                                Resume <BsBoxArrowInRight className={"w-6 ml-1"} />
                                </Link>
                            <Link href="mailto:yeohhanyi0916@gmail.com" target={"_blank"}
                            className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base">
                                Contact</Link>
                        </div>
                    </div>
                </div>
            </Layout>
        </main>
    </>
  )
}
